export const TERMINAL = {
  ACTIVATE: 'TERMINAL_ACTIVATE',
  DEACTIVATE: 'TERMINAL_DEACTIVATE',
};

export const CLASS_NAMES = {
  SEARCH: 'CLASS_NAMES/SEARCH',
};

export const TACHYONS = {
  LOAD_STYLES: 'TACHYONS/LOAD_STYLES',
};
